export function placeholder() {
  return `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi id ipsum sed nisl ultrices finibus. Donec eget diam non neque placerat pellentesque a vitae dolor. Suspendisse potenti. In hac habitasse platea dictumst. In hac habitasse platea dictumst. In ut sollicitudin massa. Sed vitae est purus. Nulla lorem leo, viverra vel facilisis ac, scelerisque eu lectus. Morbi eu consectetur eros, quis auctor est. Sed elementum sodales accumsan. Sed eleifend neque id orci faucibus vestibulum.

    Sed ullamcorper odio ac est scelerisque vestibulum. Curabitur maximus neque eu magna congue, a pellentesque risus ultrices. Ut ultricies porta erat. Aenean vitae turpis sit amet risus lacinia dapibus non ut justo. Maecenas luctus facilisis diam quis imperdiet. Proin vitae vehicula dolor. Pellentesque eu rhoncus felis. Quisque et mattis ligula, pretium posuere odio. Proin vel porttitor urna, nec congue massa. Aliquam vitae congue justo. Nunc nec velit nisi.
    
    Cras mollis, nibh a mattis accumsan, mi ligula euismod diam, sit amet sodales dui quam sit amet mi. Nunc mattis elit nec est tristique bibendum. Praesent ac luctus nisi. Sed placerat mauris ac erat tincidunt, id sagittis nisi pellentesque. Quisque tincidunt malesuada nisi, nec porta tortor vehicula sed. Nullam aliquam sagittis nunc, imperdiet tincidunt nisl ultricies id. Cras quis scelerisque orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed feugiat arcu. Donec nec sodales arcu. Nulla ultrices velit ut augue laoreet, in dignissim orci ornare. Etiam lorem lorem, aliquam vitae arcu ac, semper interdum dui. Quisque diam neque, pharetra ac vestibulum a, luctus eget erat. In lorem risus, aliquam vitae interdum at, aliquet a odio. Nullam sit amet lorem quis sapien consectetur dictum. Nulla vulputate lorem nunc, et posuere leo congue ut.
    
    Aliquam felis arcu, rhoncus vitae purus vitae, mattis vulputate tellus. Fusce tincidunt mauris lorem, eget ullamcorper tortor dignissim at. Nam purus magna, volutpat at leo ac, dignissim tincidunt enim. Etiam eget nulla nec libero ultrices tristique. Aliquam dapibus accumsan ultrices. Etiam laoreet erat non erat feugiat, vel efficitur enim viverra. Morbi malesuada varius nulla. Nunc pharetra lacinia dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec porta nibh et ante placerat rutrum. Mauris vel scelerisque nibh. Pellentesque dolor odio, aliquet sed odio in, auctor eleifend enim. Aliquam erat volutpat. Nulla sed ante at dui mollis fringilla non at leo. Donec felis urna, dapibus in congue in, sollicitudin non ipsum.
    
    In hac habitasse platea dictumst. Suspendisse aliquet varius nulla a ullamcorper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed congue malesuada libero feugiat vulputate. Aenean tempus pretium mi, vel faucibus orci. Cras eu erat eu purus eleifend commodo non in arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis tincidunt laoreet nisl, ut euismod nisi dictum lacinia. Maecenas in nunc placerat, laoreet ante eget, molestie massa. Nunc fringilla quis dui sed dignissim. Integer magna sapien, aliquet id vehicula sit amet, sodales tempus ante. Pellentesque placerat ut nibh sed semper. Fusce vestibulum tortor eget mauris aliquet, quis auctor diam fermentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi molestie feugiat turpis et blandit. Quisque elit nunc, tincidunt et fringilla in, aliquam in turpis.`
}
